version: 2.1

orbs:
  node: circleci/node@3.0.1

workflows:
  initial:
    jobs:
      - print_workspace

jobs:
  print_workspace:
    executor: node/default
    steps:
      - checkout
      - run: echo $(pwd) && echo $(ls)
