version: 2.1

orbs:
  node: circleci/node@3.0.1

workflows:
  welcome:
    jobs:
      - print_workspace

jobs:
  print_workspace:
    executor:
      name: node
      tag: "13.11"
    steps:
      - checkout
      - run:
          name: "Print cwd and ls"
          command: echo $(pwd) && echo $(ls)
