version: 2.1

orbs:
  node: circleci/node@3.0.1
  hugo: circleci/hugo@1.2.2
  awss3: circleci/aws-s3@3.0.0
  # go: circleci/go@1.7.0
  slack: circleci/slack@3.4.2

workflows:
  deploy_blog:
    jobs:
      - checkout_project:
          filters:
            branches:
              only:
                - master
      - build_blog:
          requires:
            - checkout_project
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - build_blog
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master

jobs:
  checkout_project:
    working_directory: ~/panaetius-blog/blog
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout:
          path: ~/panaetius-blog
      - slack/notify:
          message: Building latest update for https://panaetius.io
      - run: git submodule update --init --recursive
      - awss3/sync:
          from: s3://prod-panaetius-blog-static-assets/
          to: .
      - persist_to_workspace:
          root: .
          paths:
            - .
      - slack/status

  build_blog:
    working_directory: ~/panaetius-blog/blog
    executor:
      name: node/default
      tag: "14.3.0"
    steps:
      - attach_workspace:
          at: .
      - node/install-packages:
          app-dir: .
          cache-path: ./node_modules
          pkg-manager: yarn
      - node/install-packages:
          app-dir: ./themes/panaetius-theme
          cache-path: ./themes/panaetius-theme/node_modules
          pkg-manager: yarn
      - hugo/install:
          version: "0.86.0"
      - run: yarn buildBlog
      - persist_to_workspace:
          root: .
          paths:
            - .
      - slack/status

  test:
    working_directory: ~/panaetius-blog/blog
    executor:
      name: hugo/default
      tag: "0.86"
    steps:
      - attach_workspace:
          at: .
      - run: htmlproofer ./public --url-swap 'https?\:\/\/(panaetius.io):'
      - persist_to_workspace:
          root: .
          paths:
            - .
      - slack/status

  deploy:
    working_directory: ~/panaetius-blog/blog
    docker:
      - image: circleci/python:3.8.3
    steps:
      - attach_workspace:
          at: .
      - awss3/sync:
          from: ./public/
          to: s3://prod-panaetius-blog-origin
          arguments: --delete
      - slack/notify:
          message: Build complete https://panaetius.io
      - slack/status
