version: 2.1

orbs:
  node: circleci/node@3.0.1
  hugo: circleci/hugo@0.5.2

workflows:
  initial:
    jobs:
      - print_workspace

jobs:
  print_workspace:
    working_directory: "~/panaetius-blog/blog"
    executor:
      name: node/default
      tag: "14.3.0"
    steps:
      - checkout:
          path: "~/panaetius-blog"
      - run: git submodule init
      - run: git submodule update --remote
      - node/install-packages:
          app-dir: "."
          cache-path: "./node_modules"
          pkg-manager: yarn
      - node/install-packages:
          app-dir: "./themes/panaetius-theme"
          cache-path: "./themes/panaetius-theme/node_modules"
          pkg-manager: yarn
      # - run: cd blog
      - run: yarn gulp --tasks
      - hugo/install:
          version: "0.69.2"
      - run: yarn buildBlog
      - run: ll public
