version: 2.1

orbs:
  node: circleci/node@3.0.1

workflows:
  initial:
    jobs:
      - print_workspace

jobs:
  print_workspace:
    executor:
      name: node/default
      tag: "14.3.0"
    steps:
      - checkout
      - install-packages:
        app-dir: blog
        cache_path: blog/node_modules
        pkg_manager: yarn
