version: 2.1

orbs:
  node: circleci/node@3.0.1

workflows:
  initial:
    jobs:
      - print_workspace

jobs:
  print_workspace:
    executor:
      name: node/default
      tag: "14.3.0"
    steps:
      - checkout
      - run: git submodule init
      - run: git submodule update --remote
      - node/install-packages:
          app-dir: "./blog"
          cache-path: "./blog/node_modules"
          pkg-manager: yarn
      - node/install-packages:
          app-dir: "./blog/themes/panaetius-theme"
          cache-path: "./blog/themes/panaetius-theme/node_modules"
          pkg-manager: yarn
