baseURL = "http://example.org/"
title = "My New Hugo Site"
theme = "hugo-theme-chunky-poster"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Daniel Tomlinson"
  description = "Lorem ipsum dolor sit amets."
#   homepageImage = "/images/homepage-image.jpg"
  share = true
  showLanguageSwitcher = false
