baseURL = "http://example.org/"
title = "panaetius.io"
theme = "hugo-theme-chunky-poster"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
description ="Tech blog showcasing Python, Machine-Learning, Vue, Homelab and other technologies to try at home."

[languages]
[lanugages.en]
weight = 1
[languages.en.params]
LanguageName = "English"

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 4

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
header = "panaetius.io"
author = "Daniel Tomlinson"
description = "Tech blog showcasing Python, Machine-Learning, Vue, Homelab and other technologies to try at home."
homepageImage = "/images/homepage.svg"
logo = "/images/homepage.svg"
share = true
twitter = "dmot7291"
github = "dtomlinson91"

# Custom CSS and JS. Relative to /static/css and /static/js respectively.
customCSS = []
customJS = []

[params.prismJS]
enable = true

[params.commento]
enable = true
url = "https://commento.panaetius.co.uk/js/commento.js"

[imaging]
resampleFilter = "Lanczos"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]
