baseURL = "http://example.org/"
title = "Tech blog"
theme = "hugo-theme-chunky-poster"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
author = "Daniel Tomlinson"
description = "Lorem ipsum dolor sit amets. Lorem ipsum dolor sit amets."
  homepageImage = "/images/homepage.svg"
share = true
showLanguageSwitcher = false

[params.prismJS]
enable = true
# theme = "nord"

[params.commento]
enable = true
url = "https://commento.panaetius.co.uk/js/commento.js"
