baseURL = "https://panaetius.io/"
# relativeURLs = true
title = "panaetius.io"
theme = ["hugo-notice-admonition", "panaetius-theme"]
paginate = 3
summaryLength = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
enableRobotsTXT = true
description = "Tech blog showcasing Python, Rust, Homelab and various other technologies to try at home."
ignoreErrors = ["error-missing-instagram-accesstoken"]

[permalinks]
post = "post/:year/:month/:slug/"

[languages]

[lanugages.en]
weight = 1

[languages.en.params]
LanguageName = "English"

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "series"
name = "Series"
url = "/series/"
weight = 3

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 4

# [[menu.main]]
# identifier = "search"
# name = "Search"
# url = "/search/"
# weight = 4

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
header = "panaetius.io"
author = "Daniel Tomlinson"
description = "Tech blog showcasing Python, Rust, Homelab and various other technologies to try at home."
homepageImage = "/images/front-images/v0032.svg"
logo = "/images/front-images/world.svg"
share = true
twitter = "dmot7291"
github = "dtomlinson91"

[params.commento]
enable = true
url = "https://commento.panaetius.co.uk/js/commento.js"

[imaging]
resampleFilter = "Lanczos"

[outputs]
home = ["HTML", "RSS", "JSON", "Algolia"]
page = ["HTML", "RSS"]

[markup]

[markup.highlight]
# style = "monokailight"
# style = "paraiso-dark"
style = "dracula"
lineNos = true

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = [
  "title",
  "summary",
  "date",
  "publishdate",
  "expirydate",
  "permalink",
  "content",
  "fuzzywordcount",
  "readingtime"
]
params = ["categories", "tags", "authors", "series", "images"]
